# -*- coding: utf-8 -*-
"""web scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mrujr8tvybJQxrMgLLYCU02cKdNw06AH
"""

pip install beautifulsoup4

pip install lxml

pip install requests

from bs4 import BeautifulSoup

with open('home.html','r') as html_file:
  content=html_file.read()
  soup=BeautifulSoup(content,'lxml')
  tags=soup.findAll('h5')
  for t in tags:
    print(t.text)

with open('home.html','r') as html_file:
  content=html_file.read()
  soup=BeautifulSoup(content,'lxml')
  tags=soup.find_all('div',class_='card')
  for t in tags:
    tags_text=t.h5.text
    tags_price=t.a.text.split()[-1]
    print(f'{tags_text} cost is {tags_price}')

import requests

html_text=requests.get('http://www.rvrjcce.ac.in/xacademics.php').text
soup=BeautifulSoup(html_text,'lxml')
rows = soup.find_all('tr')
department_fees=[]
department_names = []
for row in rows:
    columns = row.find_all('td')
    if len(columns) > 1:
        department_name = columns[1].get_text()
        department_fee = columns[2].get_text()
        if len(department_name)>11:
          department_names.append(department_name)
          department_fees.append(department_fee)

for name,fee in zip(department_names,department_fees):
    print(name,'---',fee)

html_text=requests.get("https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&searchTextSrc=&searchTextText=&txtKeywords=python&txtLocation=").text
soup=BeautifulSoup(html_text,'lxml')
jobs = soup.find_all('li', class_='clearfix job-bx wht-shd-bx')

for job in jobs:
    company_name = job.find('h3', class_='joblist-comp-name').text.strip()
    skills = job.find('span', class_='srp-skills').text.replace('\n', ' ').strip()
    published_date = job.find('span', class_='sim-posted').text.strip()
    more_info=job.header.h2.a['href']

    if 'few' in published_date:
        print(f"Company Name: {company_name}")
        print(f"Skills Required: {skills}")
        print(f"Published Date: {published_date}")
        print(f"More Info: {more_info}")
        print("-" * 100)

from flask import Flask, render_template
import requests
from bs4 import BeautifulSoup

app = Flask(__name__)

@app.route('/')
def home():
    jobs = scrape_jobs()
    return render_template('home.html', jobs=jobs)

def scrape_jobs():
    html_text = requests.get(
        "https://www.timesjobs.com/candidate/job-search.html?searchType=personalizedSearch&from=submit&searchTextSrc=&searchTextText=&txtKeywords=python&txtLocation="
    ).text
    soup = BeautifulSoup(html_text, 'lxml')
    jobs = soup.find_all('li', class_='clearfix job-bx wht-shd-bx')
    job_list = []

    for job in jobs:
        company_name = job.find('h3', class_='joblist-comp-name').text.strip()
        skills = job.find('span', class_='srp-skills').text.replace('\n', ' ').strip()
        published_date = job.find('span', class_='sim-posted').text.strip()
        more_info = job.header.h2.a['href']

        if 'few' in published_date:
            job_list.append({
                'company_name': company_name,
                'skills': skills,
                'published_date': published_date,
                'more_info': more_info
            })

    return job_list

if __name__ == '__main__':
    app.run(debug=True)